episodes = 10000
horizon = 1000
environment = 'HumanoidBulletEnv'
agent_type = 'SAC'
replay_buffer_capacity = 1e6
random_sample_num = 1000
agent_update_batch_size = 256
checkpoint_interval = 10
checkpoint = ''
test_interval = 50
test_times = 5



[agent]
gamma = 0.99
tau = 0.005
alpha = 0.2
hidden_size = 256
target_update_interval = 1
automatic_entropy_tuning = true
learning_rate=3.0e-4